### ISSUE TITLE
Python 3.3 and 3.4 traceback

### ISSUE THREAD

**Issue by jpcirrus** [naiquevin/pipdeptree#26]
Works fine on python 2.7.8 but on both 3.3.5 and 3.4.2 I get the following traceback:

~~~python
Traceback (most recent call last):
  File "/Users/jp/.virtualenvs/python3.3/bin/pipdeptree", line 9, in <module>
    load_entry_point('pipdeptree==0.4.1', 'console_scripts', 'pipdeptree')()
  File "/Users/jp/.virtualenvs/python3.3/lib/python3.3/site-packages/pipdeptree.py", line 250, in main
    is_empty, cyclic = peek_into(cyclic_deps(pkgs, pkg_index))
  File "/Users/jp/.virtualenvs/python3.3/lib/python3.3/site-packages/pipdeptree.py", line 202, in peek_into
    a.next()
AttributeError: 'itertools._tee' object has no attribute 'next'
~~~
